### ISSUE TITLE
Get an Error when grant permission for autoinput. Windows app

### ISSUE THREAD

**Issue by urtaevS** [joaomgcd/Tasker-Permissions#26]
![err autoinput](https://github.com/joaomgcd/Tasker-Permissions/assets/66906118/96ea2c68-e6b6-4a5b-b12c-b4ca6fbd2268)

**Comment by superuser7777** [comment]
me too

Xiaome Poco F5
MIUI Global 14.0.4(14.0.4.0 TMRMIXM)
AndroidVer : 13 TKQ1.221114.001

**Comment by joaomgcd** [comment]
Hhmm, looks like you're using an older version of AutoInput? Can that be it?

**Comment by superuser7777** [comment]
> Hhmm, looks like you're using an older version of AutoInput? Can that be it?
Thank you for your quick reply.
I'm using AutoInput 3.0.2 (latest). Should I use BETA Ver?

**Comment by joaomgcd** [comment]
Nope, that should be enough... I just tried it and it worked normally for me. Are you able to grant the same permission to Tasker?

**Comment by superuser7777** [comment]
Yes, I was able to enable everything except the taskersettings tab.
I've granted all security to "tasker" as far as I can tell.
![Imgur Image](https://i.imgur.com/9JyieLi.png)

Can this be considered a MIUI14 environment issue?

**Comment by joaomgcd** [comment]
Wait, the original error was for AutoInput, you're trying to give the permission to Tasker Settings 😅 Download the latest version of that here: https://github.com/joaomgcd/TaskerSettings/releases/tag/v1.5.0

**Comment by superuser7777** [comment]
thank you & sorry, Fix it.
![Imgur Image](https://i.imgur.com/y4GeZ2h.png)

**Comment by joaomgcd** [comment]
No problem.

**Comment by nk47775** [comment]
com.joaomgcd.autoinput version 3.0.2

 Source com.android.vending
 OS Build RMX3761_14_C.65
 OS Code 34
 Device RMX3761
 Manufacturer realme
 Product RMX3761

java.lang.NullPointerException: Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.flags' on a null object reference in method 'void android.accessibilityservice.AccessibilityServiceInfo.updateDynamicallyConfigurableProperties(com.android.internal.compat.IPlatformCompat, android.accessibilityservice.AccessibilityServiceInfo)'
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.setServiceInfo(IAccessibilityServiceConnection.java:1125)
	at android.accessibilityservice.AccessibilityService.sendServiceInfo(AccessibilityService.java:2588)
	at android.accessibilityservice.AccessibilityService.setServiceInfo(AccessibilityService.java:2571)
	at com.joaomgcd.autoinput.service.ServiceAccessibilityV2.N0(SourceFile:5)
	at com.joaomgcd.autoinput.service.ServiceAccessibilityV2.M0(SourceFile:1)
	at com.joaomgcd.autoinput.service.ServiceAccessibilityV2.onAccessibilityEvent(SourceFile:23)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2744)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.lambda$onAccessibilityEvent$2(AccessibilityService.java:2930)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.$r8$lambda$09cnCCQeC7txVafv5NeCrjYkmcY(Unknown Source:0)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper$$ExternalSyntheticLambda8.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8394)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:640)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.accessibilityservice.AccessibilityServiceInfo.updateDynamicallyConfigurableProperties(AccessibilityServiceInfo.java:806)
	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.setServiceInfo(AbstractAccessibilityServiceConnection.java:490)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:491)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by joaomgcd** [comment]
@nk47775  Can you please try this version? https://drive.google.com/file/d/1_MCmNfnK4FpFB7HFOgkQxNKbtbmbb8Rs/view
