### ISSUE TITLE
Error on Reload Devices / Permissions

### ISSUE THREAD

**Issue by jdhott** [joaomgcd/Tasker-Permissions#6]
I receive the following error consistently when I click Reload Devices / Permissions.
- Running Permissions App on M1 Mac with MacOS 12.0.1 (Monterey) 
- Connected to Samsung Galaxy S10 with Android V11

Unexpected Error: Cannot read property '1' of null. Please contact developer about it.

Trace:
TypeError: Cannot read property '1' of null
at file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:142:60
at Array.map (<anonymous>)
at file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:137:41
at async App.renderDevices (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:58:28)
at async App.renderAll (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:44:9)
at async App.onRequestReloadDevices (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:211:9)
at async EventBus.sendToRegistered (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/js/eventbus.js:84:5)
at async EventBus.post (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/js/eventbus.js:94:7)
at async Function.post (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/js/eventbus.js:15:10)

**Comment by joaomgcd** [comment]
Hi there, thanks for the report! Can you please try this version? https://drive.google.com/open?id=16LzNqDbt3WqAyCV2CdnD-dD7A5QLrWQ3

**Comment by jdhott** [comment]
Do you have a MacOS version? The link was for Windows.

**Comment by kencx** [comment]
Hi, I'm facing a similar issue for Linux Ubuntu 21.04 with a Pixel 3, Android v12.

![Dec24-18:09:29](https://user-images.githubusercontent.com/42935499/147343653-578facbe-8479-46ac-a5e8-b25bf2c6239b.png)

**Comment by enstain-tm** [comment]
I am having the same issue on Ubuntu 20.04LTS

**Comment by nortuzar** [comment]
Same here on windows 10

**Comment by Seamndel** [comment]
Same Issue Windows 11

**Comment by joaomgcd** [comment]
For people on Window, does this version fix it? https://drive.google.com/open?id=16LzNqDbt3WqAyCV2CdnD-dD7A5QLrWQ3

**Comment by lentm88** [comment]
Yes, the new version fixed the issue on my Windows 10 Pro 21H2. Thank you!

**Comment by lentm88** [comment]
> For people on Window, does this version fix it? https://drive.google.com/open?id=16LzNqDbt3WqAyCV2CdnD-dD7A5QLrWQ3

Yes, the new version fixed the issue on my Windows 10 Pro 21H2. Thank you!

**Comment by joaomgcd** [comment]
Great! :)

**Comment by kencx** [comment]
Is there a fix for Linux?

**Comment by joaomgcd** [comment]
Hi, please check here: https://github.com/joaomgcd/Tasker-Permissions/releases/tag/v0.2.0
