### ISSUE TITLE
Cannot read property "1" of null.

### ISSUE THREAD

**Issue by rcthomas69** [joaomgcd/Tasker-Permissions#9]
![error](https://user-images.githubusercontent.com/16517967/157511925-79f94396-8609-4b4c-9b0d-c7520df31ca7.jpg)

**Comment by joaomgcd** [comment]
Hi. That should be fixed in the latest version of the app. Are you sure you're using that?

**Comment by alexandreminot2** [comment]
Hello,

I have the same problem with the 0.1.0 mac build:

Unexpected Error: Cannot read property '1' of null. Please contact developer about it.

Trace:
TypeError: Cannot read property '1' of null
at file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:142:60
at Array.map (<anonymous>)
at file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:137:41
at async App.renderDevices (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:58:28)
at async App.renderAll (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:44:9)
at async App.render (file:///Applications/com.joaomgcd.taskerpermissions.app/Contents/Resources/app.asar/app/app.js:38:9)

I'm running Mac OS 12.2.1 (21D62) on an intel processor. let me know of I can help.

**Comment by joaomgcd** [comment]
Can you please install the latest version and try again? Thanks

**Comment by alexandreminot2** [comment]
Yes, it works now. 
Many thanks,
Best,
Alex
